import type { Metadata } from 'next';
// import { Geist, Geist_Mono, Inter } from "next/font/google";
import './globals.css';
import { cn } from '@/lib/utils';
import { vazir } from '@/lib/fonts';
import QueryProvider from '@/providers/QueryProvider';
import { Header } from '@/components/features/header/Header';
import { MobileHeader } from '@/components/features/header/MobileHeader';
import { MobileBottomNav } from '@/components/features/header/MobileBottomNav';

// const inter = Inter({subsets:['latin'],variable:'--font-sans'});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="fa" className={cn('h-full', vazir.variable)}>
      <body className={cn('min-h-full flex flex-col ', vazir.className)}>
        <Header></Header>
        <MobileHeader></MobileHeader>
        <MobileBottomNav />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
