import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { vazir } from '@/lib/fonts';
import QueryProvider from '@/providers/QueryProvider';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="fa" className={cn('h-full', vazir.variable)}>
      <body className={cn('min-h-full flex flex-col ', vazir.className)}>
        <QueryProvider>{children}</QueryProvider>
        <Toaster position="top-center" dir="rtl" />
      </body>
    </html>
  );
}
